function init(self)
	local forest = descend.get_forest()
	print("===== forest ==== ")
	pprint(forest)

	
	local tree = descend.get_tree("/go1")
	print("===== tree ==== ")
	pprint(tree)
end


function update(self, dt)
	-- duration info can be seen in the web profiler
	local forest = descend.get_forest()
	local tree = descend.get_tree("/go1")
end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
end
